security:
  security-policies:
    - policy-name: DATA_READER
      effective-date: 2017-3-15
      apply-on: report, user
      password-complexity: MODERATE
    - policy-name: ADMIN
      effective-date: 2020-3-15
      apply-on: admin
      password-complexity: HIGH